
name: fastai-lessons-binder-environment
channels:
  - pytorch
  - fastai
  - conda-forge
dependencies:
  - fastai
 # - matplotlib
 # - pandas
 # - numpy
 # - pip
 # - pip:
 #     - pytorch pytorch-nightly
 #     - fastai>=1.0.42

